package day12;

public class Exception01 {

	public static void main(String[] args) {
		/* Exception : 예외처리
		 * 실행시 발생할 수 있는 예외를 처리하여 정상처리로 유지시키는 기능.
		 * try ~ catch ~ finally (finally는 선택)
		 * try : 예외를 발생할 가능성이 있는 구문 작성
		 * catch : try구문에서 예외가 발생했을때 예외처리
		 * finally : try구문 외 반드시 실행되어야하는 구문이 있을 경우(없으면 사용X)
		 * */
		
		
		double res = 0;
		
		int num = 10;
		int num1 = 0;
		
		try {
			res = num /num1;
			System.out.println(res);
		} catch (Exception e) {
			System.out.println("0으로 나누었습니다. exception 발생!!!!");
		}
	
	}

}
